document:

  title: Azure-Sdk

  original:
    url: https://github.com/Azure/azure-sdk.git
    branch: main

  translated:
    url: https://github.com/Azure/azure-sdk-korean.git
    translated-branch: main

keys:
  translate-api: update-api-at-github-action-secret